# Generated by Django 2.0.5 on 2018-07-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='knowledgePoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kpNmae', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='knowledgeQue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kpId', models.CharField(max_length=50)),
                ('queId', models.CharField(max_length=50)),
            ],
        ),
    ]
