# Generated by Django 2.0.5 on 2018-07-08 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgePoint', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='knowledgepoint',
            old_name='kpNmae',
            new_name='kpName',
        ),
    ]
