# Generated by Django 2.0.5 on 2018-07-08 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgePoint', '0002_auto_20180708_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgeque',
            name='kpId',
            field=models.IntegerField(max_length=50),
        ),
    ]
