# Generated by Django 2.0.5 on 2018-07-08 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgePoint', '0003_auto_20180708_1308'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='knowledgePoint',
            new_name='zsd',
        ),
        migrations.RenameModel(
            old_name='knowledgeQue',
            new_name='zsdTh',
        ),
    ]
