# Generated by Django 2.0.5 on 2018-07-08 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgePoint', '0004_auto_20180708_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zsd',
            name='kpName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='zsdth',
            name='kpId',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='zsdth',
            name='queId',
            field=models.IntegerField(),
        ),
    ]
