# Generated by Django 2.0.5 on 2018-07-08 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgePoint', '0006_auto_20180708_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zsdth',
            name='kpId',
            field=models.CharField(max_length=50),
        ),
    ]
