# Generated by Django 2.0.5 on 2018-07-05 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreSubmit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queId', models.CharField(max_length=50)),
                ('maxS', models.IntegerField()),
                ('minS', models.IntegerField()),
                ('avg', models.FloatField()),
                ('bzc', models.IntegerField()),
            ],
        ),
    ]
